version: '3.9'
services:
  postgres:
    image: postgres:13
    container_name: publication_postgres
    environment:
      POSTGRES_DB: '${POSTGRES_DB}'
      POSTGRES_USER: '${POSTGRES_USER}'
      POSTGRES_PASSWORD: '${POSTGRES_PASSWORD}'
    ports:
      - '2345:5432'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}']
      interval: 10s
      timeout: 5s
      retries: 5
  server:
    build: ./server
    container_name: publication_server
    environment:
      DB_HOST: '${POSTGRES_HOST}'
      DB_NAME: '${POSTGRES_DB}'
      DB_USER: '${POSTGRES_USER}'
      DB_PASSWORD: '${POSTGRES_PASSWORD}'
      DB_PORT: 5432
    ports:
      - '4000:4000'
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ['CMD-SHELL', 'curl --fail http://localhost:4000/api']
      interval: 5s
      timeout: 3s
      retries: 3
  app:
    build: ./app
    container_name: publication_app
    ports:
      - '3000:3000'
    depends_on:
      - server